# Generated by Django 4.2 on 2026-08-15 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='buy_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sell_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
