# Generated by Django 4.2 on 2026-08-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_buy_date_portfolio_sell_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='exit_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='realized_brokerage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='realized_gross_pnl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='realized_net_pnl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('exited', 'Exited')], default='active', max_length=10),
        ),
    ]
